$(document).ready(function(){
		$(".bang_top").hide();
		$('.left_cebian').hide();
		$(document).scroll(function(){
			//alert($(document).scrollTop()>0);
			if($(document).scrollTop()>800){
				$(".bang_top").slideDown('fast');
				$('.left_cebian').show('fast');
				$('.left_cebian').css({'width':'36px','height':'369px','opacity':'1'});
		   }else{
				$(".bang_top").slideUp('fast');
				$('.left_cebian').css({'width':'0px','height':'0px','opacity':'0'});
				$('.left_cebian').fadeOut();   
		   }
		});
		$('.to_top').click(function(){
			$("body,html").animate({scrollTop:'0px'},400);
		});
});
